apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.team}}-${{values.application_id}}-app
  description: ${{values.description}}
  annotations:
    github.com/project-slug: ${{values.repoOwner}}/${{values.team}}-${{values.application_id}}-app
  links:
    - url: https://${{values.containerRegistry}}/${{values.repoOwner}}/${{values.team}}-${{values.application_id}}
      title: Container Image
      icon: docker
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.team}}
