apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.team}}-${{values.application_id}}
  description: ${{values.description}}
  annotations:
    github.com/project-slug: ${{values.repoOwner}}/${{values.team}}-${{values.application_id}}
    argocd/app-name: ${{values.application_id}}
  links:
    - url: https://github.com/${{values.repoOwner}}/${{values.appRepoName}}
      title: Application Source
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.team}}
  dependsOn:
    - component:${{values.team}}-${{values.application_id}}-app
